language: julia

julia:
    - 1.4
    - 1.5
    - nightly

os:
    - linux
    - osx
    - windows

arch:
    - amd64
    #- arm64

notifications:
    email: false
  
matrix:
    allow_failures:
        - julia: nightly

script:
    - JULIA_DEBUG=PersistentCollections JULIA_NUM_THREADS=999999 julia --project --check-bounds=yes -e 'import Pkg; Pkg.activate("."); Pkg.test(coverage=true)'

after_success:
    - julia --project -e 'import Pkg; Pkg.add("Coverage")'
    - julia --project -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'
