name = "PersistentCollections"
uuid = "84dc0e8b-87a2-413f-9462-a65634c44495"
authors = ["Zalan Blenessy <zalan.blenessy@gmail.com>"]
version = "0.2.0"

[deps]
LMDB_jll = "6206cf0b-f360-5984-af49-5437264c140e"

[compat]
LMDB_jll = "0.9"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test", "BenchmarkTools"]
